### ISSUE TITLE
Problem with typings, Microsoft is not defined.

### ISSUE THREAD

**Issue by mouadcherkaoui** [richdizz/ionic2-angular2-msgraph#1]
Hello,

   first of all thank you for the tutorial and the code sample.
   i tried to use this example as starting point for one of my projects, but each time I have an issue with typescript définitions, I installed the définitions dt~cordova-plugin-ms-adal, but the problem persist,
is there a breaking changes with the last version of the adal plugin, and is there another Library to use to replace the adal plugin for example KurveJs ? 

Thanks in advance.

**Comment by ersurajnegi** [comment]
I am also facing the Same issue.
Please provide some solution for this?

**Comment by bradma** [comment]
Cordova plugins don't seem to load if you are running through the browser (ionic serve)

Try building or running the code on an actual device.

Hope that helps!
